### ISSUE TITLE
Could you document the purpose for each exposed port?

### ISSUE THREAD

**Issue by nodew** [kmahyyg/ztncui-aio#10]
In the Dockerfile, it exposes 4 ports
```
EXPOSE 3000/tcp
EXPOSE 3180/tcp
EXPOSE 8000/tcp
EXPOSE 3443/tcp
```
3443 is for https, no doubt.

But for 3000/3180/8000, what's the difference?

**Comment by kmahyyg** [comment]
RTFM

**Comment by kmahyyg** [comment]
One thing that currently is not in document is that 8000 is for backward compatibility according to upstream.

**Comment by kmahyyg** [comment]
> RTFM

I'm so sorry for this rude reply. I'm currently experiencing something really bad.

Actually everything you want is inside the readme file under the root of this repository. Feel free to ask more.

**Comment by nodew** [comment]
Never mind, understandable.
Actually, I'm getting the following error after starting the docker container:
```
$ curl http://localhost:3000
curl: (52) Empty reply from server
```
I thought it might be caused by false port binding, but it seems there's other causes.

**Comment by kmahyyg** [comment]
> Never mind, understandable. Actually, I'm getting the following error after starting the docker container:
> 
> ```
> $ curl http://localhost:3000
> curl: (52) Empty reply from server
> ```
> 
> I thought it might be caused by false port binding, but it seems there's other causes.

May I know how do you start up the container and it's startup configuration?

**Comment by nodew** [comment]
Following the README, https://github.com/key-networks/ztncui-aio

```
docker run -d -p9993:9993/udp -p3443:3443 -p3180:3180 -p:3000:3000 \
    -v /mydata/ztncui:/opt/key-networks/ztncui/etc \
    -v /mydata/zt1:/var/lib/zerotier-one \
    --env-file ./denv \
    --name ztncui \
    keynetworks/ztncui
```

Here the denv file
```
NODE_ENV=production
HTTPS_PORT=3443
HTTP_PORT=3000
MYDOMAIN=xxx
MYADDR=xxx
```

Docker ps
```

Curl in the host machine, it failed
```
$ curl http://localhost:3000
curl: (52) Empty reply from server
```
$ docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED       STATUS       PORTS
 NAMES
b01b8a244d3e   keynetworks/ztncui   "/usr/bin/supervisord"   4 hours ago   Up 4 hours   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp, 0.0.0.0:3180->3180/tcp, :::3180->3180/tcp, 0.0.0.0:3443->3443/tcp, :::3443->3443/tcp, 8000/tcp, 0.0.0.0:9993->9993/udp, :::9993->9993/udp   ztncui
```
curl works as expected inside docker
```bash
$ docker exec -it ztncui bash
root@b01b8a244d3e:/# curl http://localhost:3000
<!DOCTYPE html><html lang="en"><head><title>ztncui</title><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="/bscss/bootstrap.min.css"><link rel="stylesheet" href="/stylesheets/style.css"><script src="/jqjs/jquery.min.js"></script><script src="/bsjs/bootstrap.min.js"></script></head><body><nav class="navbar navbar-inverse navbar-fixed-top"><div class="container-fluid"><div class="navbar-header"><button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#BarNav"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand" href="https://key-networks.com" target="_blank"><img src="/images/key-logo.svg" alt="Key Networks logo" height="25px" width="25px" style="display: inline"> Key Networks</a></div><div class="collapse navbar-collapse" id="BarNav"><ul class="nav navbar-nav"></ul><ul class="nav navbar-nav navbar-right"><li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li></ul></div></div></nav><div class="container" style="margin-top:50px"><div class="row"><div class="col-sm-12"><h1>ztncui</h1><h2><a href="https://zerotier.com" target="_blank">ZeroTier </a>network controller UI</h2></div></div></div></body></html>
```

**Comment by kmahyyg** [comment]
well, try `http://127.0.0.1:3000` or `http://<MYDOMAIN>:3000`, don't forget to set `/etc/hosts` to 127.0.0.1 with your domain.

**Comment by nodew** [comment]
Both doesn't work.

**Comment by nodew** [comment]
By the way, `curl -k https://localhost:3443` works.

**Comment by kmahyyg** [comment]
oh wait...
<img width="867" alt="CleanShot 2022-01-03 at 20 28 54@2x" src="https://user-images.githubusercontent.com/16604643/147930530-f1ef69fc-377d-4785-b2ca-151fe98da495.png">

I forget to say that if you not set `HTTP_ALL_INTERFACES`, the 3000 port will only listen to 127.0.0.1 inside the container. It's about transport security concern.

**Comment by kmahyyg** [comment]
You could easily check this by:

![image](https://user-images.githubusercontent.com/16604643/147930848-5f0a5cc2-dbd4-46d2-bdc4-60379efe92ec.png)

**Comment by kmahyyg** [comment]
Does this solve your problem?

**Comment by nodew** [comment]
Yes, it's the root cause.
