### ISSUE TITLE
No filtering. was doing a pen test before roll out, burpsuite caused it to create a ton of jibberish networks.

### ISSUE THREAD

**Issue by xelerated** [kmahyyg/ztncui-aio#17]
![image](https://user-images.githubusercontent.com/5711753/231883621-eb2dad40-c873-41e4-a458-8dd66bb1dd89.png)

**Comment by xelerated** [comment]
this is in a docker, can some kind of WAF be used in unison? or any sort of fix?

**Comment by kmahyyg** [comment]
I think you need to review the knowledge of pentesting. Since I'm working in cybersecurity field, I cannot see any evidence there's a real vuln here that affect confidentiality or integrity or availability. Also, I'm not the developer of ztncui, I just made this dockerfile.

**Comment by kmahyyg** [comment]
Also, we've enabled private security vuln report feature on GitHub. If you can confirm there's actually a vuln here like SSTI or something else, use this feature and please close this issue.

**Comment by xelerated** [comment]
Well as a pen tester for 15 years now, how can loading up your networks page with hundreds of garbage entries not be a vuln? not quite a DoS but will sure make finding your desired networks hell.

**Comment by xelerated** [comment]
also lol 
![image](https://user-images.githubusercontent.com/5711753/232047442-e5305c75-c135-4648-a507-c0d6b135f70d.png)

**Comment by kmahyyg** [comment]
I don't care about this shortest time of period. And also, since ZT backend accept this as a network name, none of my business here.

**Comment by kmahyyg** [comment]
If you cannot give me a profiling or something else that actually break something, then I would not accept it.

**Comment by kmahyyg** [comment]
And also, if you say "loading up your networks page with hundreds of garbage entries" is a vuln, then I have bunches of these vuln, then what if I submit them to BugCrowd or H1? You must know that.

Also, This panel, in my personal point of view, IS NOT meant to exposed publicly without any protection in front.
