### ISSUE TITLE
ztncui docker has no arm64 version

### ISSUE THREAD

**Issue by shiny996** [kmahyyg/ztncui-aio#18]
I'm trying to git clone and docker build . -t keynetworks/ztncui the response is as follows, my machine is oracle arm
2023-04-27 01:01:29,696 INFO supervisord started with pid 1
2023-04-27 01:01:30,699 INFO spawned: 'ztone' with pid 7
2023-04-27 01:01:30,701 INFO spawned: 'ztncui' with pid 8
2023-04-27 01:01:30,703 INFO spawned: 'ztplaserv' with pid 9
2023-04-27 01:01:32,436 INFO exited: ztncui (exit status 1; not expected)
2023-04-27 01:01:33,440 INFO spawned: 'ztncui' with pid 61
2023-04-27 01:01:33,805 INFO exited: ztncui (exit status 1; not expected)
2023-04-27 01:01:35,809 INFO spawned: 'ztncui' with pid 78
2023-04-27 01:01:36,155 INFO exited: ztncui (exit status 1; not expected)
2023-04-27 01:01:39,160 INFO spawned: 'ztncui' with pid 95
2023-04-27 01:01:39,514 INFO exited: ztncui (exit status 1; not expected)

**Comment by kmahyyg** [comment]
For the building process, this logging should not occur. Are you actually trying to run using `docker run`?

If it is from `docker build`, please submit full log in a text file and attach them here.
If it is from `docker run`, please copy `/var/log/docker-*.log` and compress them into a zip file and attach them here.

We really appreciate your feedback. Thanks!

**Comment by kmahyyg** [comment]
Uhhhh, Sorry. I didn't catch the title that you've already mentioned that you are currently running on ARM64 machine. If so, currently, this repo is currently NOT expected to support ARM64.

https://github.com/kmahyyg/ztncui-aio/blob/6e2f2673727cfc0667344d08c00a9bc45c42e790/Dockerfile#L22

I guess there might be some issues on the UI developer side.

Please still submit log files for me to debug. Also, feel free to submit a PR to solve this issue.

**Comment by shiny996** [comment]
bulid logs:
 docker build . -t keynetworks/ztncui
[+] Building 116.3s (27/27) FINISHED                                                                                              
 => [internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                              0.0s
 => [internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 3.09kB                                                                                       0.0s
 => [internal] load metadata for docker.io/library/debian:bullseye-slim                                                      2.9s
 => [internal] load metadata for docker.io/library/golang:bullseye                                                           2.8s
 => [internal] load build context                                                                                            0.0s
 => => transferring context: 7.63kB                                                                                          0.0s
 => [argong 1/5] FROM docker.io/library/golang:bullseye@sha256:595c9af0430dd84bad33020e7e9e328af4bd1a1aabd46a03b5bf6f252cd  19.0s
 => => resolve docker.io/library/golang:bullseye@sha256:595c9af0430dd84bad33020e7e9e328af4bd1a1aabd46a03b5bf6f252cdbecf3     0.1s
 => => sha256:8f993d5b17f32f4b8a535c25e182e5d8412625beee450e513ca57036e8fdd6dc 54.68MB / 54.68MB                             1.8s
 => => sha256:3ae8c6b39a3b9b675a35ea32f6a5aa6d0297e9fcc95c55b059ecebde0244d034 81.40MB / 81.40MB                             3.5s
 => => sha256:6a3f85fa5fea0527605546d7324a29e8beeebb43c46cf797c0a6e40e687ea7bd 154B / 154B                                   0.2s
 => => sha256:595c9af0430dd84bad33020e7e9e328af4bd1a1aabd46a03b5bf6f252cdbecf3 1.86kB / 1.86kB                               0.0s
 => => sha256:97a9f05f43c85f70dea2d17e2ce4b6887693d5267d2f000c6b34bba95c505eeb 1.79kB / 1.79kB                               0.0s
 => => sha256:dc80b8cdbfd36cb20231d807a50d704945d1df4da8f6e23197ccfcb629970491 53.71MB / 53.71MB                             0.7s
 => => sha256:5884e7f2c8c61aa845de4902fc29639b58861ae6c2d80bafe82082c0456c0740 5.15MB / 5.15MB                               0.5s
 => => sha256:1b792b01ed3c8dc1488cd8aac41ab7d49bb17f3fa22b2e6c846078cec81a1c00 10.87MB / 10.87MB                             0.3s
 => => sha256:d2f204467e745d440f7610e6a5009c95a72f381c518c8df0aab70a4ea9f7ef19 7.33kB / 7.33kB                               0.0s
 => => sha256:1e674eb0be8ba89b1be881f27765e57c0ba1f99c9ba25ffe9d5fcbd0003ebed8 95.44MB / 95.44MB                             5.5s
 => => extracting sha256:dc80b8cdbfd36cb20231d807a50d704945d1df4da8f6e23197ccfcb629970491                                    2.1s
 => => extracting sha256:5884e7f2c8c61aa845de4902fc29639b58861ae6c2d80bafe82082c0456c0740                                    0.2s
 => => extracting sha256:1b792b01ed3c8dc1488cd8aac41ab7d49bb17f3fa22b2e6c846078cec81a1c00                                    0.2s
 => => extracting sha256:8f993d5b17f32f4b8a535c25e182e5d8412625beee450e513ca57036e8fdd6dc                                    2.1s
 => => extracting sha256:3ae8c6b39a3b9b675a35ea32f6a5aa6d0297e9fcc95c55b059ecebde0244d034                                    1.9s
 => => extracting sha256:1e674eb0be8ba89b1be881f27765e57c0ba1f99c9ba25ffe9d5fcbd0003ebed8                                    3.6s
 => => extracting sha256:6a3f85fa5fea0527605546d7324a29e8beeebb43c46cf797c0a6e40e687ea7bd                                    0.0s
 => [builder 1/4] FROM docker.io/library/debian:bullseye-slim@sha256:9404b05bd09b57c76eccc0c5505b3c88b5feccac808d9b193a4fba  5.6s
 => => resolve docker.io/library/debian:bullseye-slim@sha256:9404b05bd09b57c76eccc0c5505b3c88b5feccac808d9b193a4fbac87bb447  0.1s
 => => sha256:9404b05bd09b57c76eccc0c5505b3c88b5feccac808d9b193a4fbac87bb44745 1.85kB / 1.85kB                               0.0s
 => => sha256:c115e796a6013213e61112da62f6da7f0a3390df894ade3434d0784f56b292cf 529B / 529B                                   0.0s
 => => sha256:f37d1db70154bfdbe470c362201f9378eebd1c6476257f1be037f7d5e20f8453 1.48kB / 1.48kB                               0.0s
 => => sha256:ebc3dc5a2d72427c585c8cda7574a75d96e04b9a37572bd3af0bff905abefbb9 30.06MB / 30.06MB                             0.9s
 => => extracting sha256:ebc3dc5a2d72427c585c8cda7574a75d96e04b9a37572bd3af0bff905abefbb9                                    1.7s
 => [builder 2/4] ADD VERSION .                                                                                              5.0s
 => [runner  2/14] RUN apt update -y &&     apt install curl gnupg2 ca-certificates unzip supervisor net-tools procps --no  44.1s
 => [builder 3/4] WORKDIR /build                                                                                             1.9s
 => [builder 4/4] RUN apt update -y &&     apt install curl gnupg2 ca-certificates zip unzip build-essential git --no-inst  98.2s
 => [argong 2/5] WORKDIR /buildsrc                                                                                          13.6s
 => [argong 3/5] COPY argon2g /buildsrc/argon2g                                                                              0.3s
 => [argong 4/5] COPY fileserv /buildsrc/fileserv                                                                            0.0s
 => [argong 5/5] RUN mkdir -p binaries &&     cd argon2g &&     go mod download &&     go build -ldflags='-s -w' -trimpath  19.3s
 => [runner  3/14] WORKDIR /opt/key-networks/ztncui                                                                          0.9s
 => [runner  4/14] COPY --from=builder /build/artifact.zip .                                                                 0.3s 
 => [runner  5/14] RUN unzip ./artifact.zip &&     rm -f ./artifact.zip                                                      1.0s 
 => [runner  6/14] COPY --from=argong /buildsrc/binaries/gosu /bin/gosu                                                      0.1s 
 => [runner  7/14] COPY --from=argong /buildsrc/binaries/minica /usr/local/bin/minica                                        0.1s 
 => [runner  8/14] COPY --from=argong /buildsrc/binaries/argon2g /usr/local/bin/argon2g                                      0.0s 
 => [runner  9/14] COPY --from=argong /buildsrc/binaries/fileserv /usr/local/bin/gfileserv                                   0.1s 
 => [runner 10/14] COPY start_zt1.sh /start_zt1.sh                                                                           0.0s 
 => [runner 11/14] COPY start_ztncui.sh /start_ztncui.sh                                                                     0.0s 
 => [runner 12/14] COPY supervisord.conf /etc/supervisord.conf                                                               0.0s 
 => [runner 13/14] RUN chmod 0755 /bin/gosu &&     chmod 0755 /usr/local/bin/minica &&     chmod 0755 /usr/local/bin/argon2  0.3s 
 => exporting to image                                                                                                       0.5s 
 => => exporting layers                                                                                                      0.4s 
 => => writing image sha256:5c09470dbe6c17a11fbf3ce7ed1ae66c49093761265921123982ab9414463265                                 0.0s
 => => naming to docker.io/keynetworks/ztncui

**Comment by shiny996** [comment]
> Uhhhh, Sorry. I didn't catch the title that you've already mentioned that you are currently running on ARM64 machine. If so, currently, this repo is currently NOT expected to support ARM64.
> 
> https://github.com/kmahyyg/ztncui-aio/blob/6e2f2673727cfc0667344d08c00a9bc45c42e790/Dockerfile#L22
> 
> I guess there might be some issues on the UI developer side.
> 
> Please still submit log files for me to debug. Also, feel free to submit a PR to solve this issue.

After I changed node${NODEJS_MAJOR}-linux-x64 to node${NODEJS_MAJOR}-linux-arm64, I saved it as a Dockerfile.aarch64 file. After rebuilding, it can now run on the machine.

**Comment by kmahyyg** [comment]
Will optimize later, case closed.
