### ISSUE TITLE
zerotier-one-1.6.2 is installed instead of 1.6.4

### ISSUE THREAD

**Issue by key-networks** [kmahyyg/ztncui-aio#2]
@kmahyyg I'm trying to build a new ztncui-aio based on v0.7.0 of ztncui, but for some reason I haven't been able to fathom, the runner installs zerotier-one-1.6.2.  It only installs zerotier-one-1.6.4 if I enter the running container and manually apt update and apt install zerotier-one again.

I don't understand it because the runner starts with an apt update and ztone.sh has an apt update after installing the zt-sources-list.  Do you have any ideas?  Thanks.

**Comment by kmahyyg** [comment]
Hello, is there any reproducible code I could have a look? And also, my mother language is not English, sorry for that, what's the meaning of `fathom`?

**Comment by key-networks** [comment]
Sorry... fathom means to figure something out or understand it.  I'll submit a PR on my fork and send you the link.

**Comment by key-networks** [comment]
Here is the PR for branch ztncui-0.7.0 https://github.com/key-networks/ztncui-aio/pull/4

**Comment by key-networks** [comment]
Thanks for testing.
