### ISSUE TITLE
请问一下文档能不能写清楚点啊

### ISSUE THREAD

**Issue by shuncon** [kmahyyg/ztncui-aio#24]
emmm 
中文的

**Comment by kmahyyg** [comment]
per README:

> The upstream repo (https://github.com/kmahyyg/ztncui-aio) only accept Issues and PRs in English. Other languages will be closed directly without any further notice. If you come from some non-English countries, use Google Translate, and state that at the beginning of the text body.

**Comment by shuncon** [comment]
文档写的太烂了
