### ISSUE TITLE
aren't able to initiate

### ISSUE THREAD

**Issue by potus2030** [kmahyyg/ztncui-aio#30]
In Armbian, errors occurred, dockr logs showing:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service entryinit: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-sudoc: fatal: unable to get exit status from server: Operation timed out
s6-rc: warning: unable to start service entryinit: command exited 111

**Comment by kmahyyg** [comment]
Plaese submit your detailed software information:
- Hardware model (since you're currently running on a ARM64 device)
- OS Distro and its version
- Startup command (If you use env file/config file, please attach. make sure to redact sensitive information)

**Comment by kmahyyg** [comment]
closed due to stale.
