### ISSUE TITLE
 ztncui显示被连接的主机都在线，但是无法相连？

### ISSUE THREAD

**Issue by lxwsdtc88** [kmahyyg/ztncui-aio#34]
你好，首先抱歉不能使用英语描述问题：

    最近，我在京东云的轻量服务器搭建本项目的docker 并且保证打开了9993/udp端口，另外两个终端使用生成的planet也在ztncui显示已经在线，同时这两个终端都作为路由，管理下面各自网段，但是奇怪的是，这两个网段中的网络并不能相互访问，同时我注意的到，这两个终端的接口信息是inet6，但是我的云主机用的ip是ipv4，同时私有planet也是基于ipv4制作的，这一现象不知道是否与该问题有关。
   不吝赐教，谢谢

**Comment by kmahyyg** [comment]
Please check document on:

- https://docs.zerotier.com/start#authorize-your-device
- https://key-networks.com/ztncui/

and make sure the member in your virtual network is set to be authorized and get IPv4 address assigned.

Also, please check your security group settings on your JD Cloud console, make sure corresponding data transfer is allowed: https://zerotier.atlassian.net/wiki/spaces/SD/pages/249167873/How+do+I+allow+ZeroTier+through+my+corporate+firewall

It would be better if you could choose correct issue template and fill information required as template said, also, please attach network information screenshot if applicable (your private information should be redacted before upload).

**Comment by lxwsdtc88** [comment]
Hello, I’ve studied the document you provided, but I still haven’t solved my problem。Here’s the translation of the provided screenshot
![screenshot-1712466652903](https://github.com/kmahyyg/ztncui-aio/assets/54741527/c4ec2e05-b538-4e1a-94a2-71d7acc9e236)
it's looks worked,but they can't visit each
![blob](https://github.com/kmahyyg/ztncui-aio/assets/54741527/83079a32-7101-4160-a1e9-42879aa66305)
![screenshot-1712466821639](https://github.com/kmahyyg/ztncui-aio/assets/54741527/fbb83892-8139-4632-a015-1f85703826fe)
![screenshot-1712467215321](https://github.com/kmahyyg/ztncui-aio/assets/54741527/703c6a39-2023-45f1-85e2-521b4b352312)
![screenshot-1712467278427](https://github.com/kmahyyg/ztncui-aio/assets/54741527/ff5b259c-175a-4fda-b8c0-42718de08304)

**Comment by kmahyyg** [comment]
Please allow "Active Bridge" and assign IP yourself according to document: https://docs.zerotier.com/bridging#configure-the-device-in-zerotier-central

For best practice, please also **DO NOT USE** non-RFC1918 IP range as your private network address.

Note: this project does NOT provide support to ZT usage issue, and only provide troubleshooting to docker image due to packaging issue, and is designated for advanced users. Please make sure you understand how ZT works, or else, I strongly recommend you to walkthrough original ZT central before starting from here.

**Comment by kmahyyg** [comment]
It also seems that your client does NOT receive an IP from control plane:

IPv4 address absent:
![20240407-142359-CleanShot-008662](https://github.com/kmahyyg/ztncui-aio/assets/16604643/09c20afe-b242-47d3-b92e-a075d7a790d5)

If correctly assigned:
![20240407-142503-Google Chrome-008664@2x](https://github.com/kmahyyg/ztncui-aio/assets/16604643/35f6ffe3-3900-42b6-bfaa-25042a500ada)
