### ISSUE TITLE
[BUG?] Cannot assign public IPv6 address for leaf nodes

### ISSUE THREAD

**Issue by DreamChaser-luzeyu** [kmahyyg/ztncui-aio#36]
**Describe the bug**
Cannot assign public IPv6 address for leaf nodes

**To Reproduce**
- Go to assignment pool and add a public IPv6 range, neither the LEAF node nor the webui get a valid IPv6 in that range.
- Click the IP address and assign a IPv6 manually, the static IPv6 address appears on the webui.
- If the IPv6 address starts with `fd::/8` then the IPv6 address is successfully assigned on the client.
- If the IPv6 address is a public address, the IPv6 address does not appear on the client.

**Expected behavior**
The leaf client can be assigned a public IPv6 address.

**Comment by kmahyyg** [comment]
Please contact Zerotier Official. Not related to this docker image packaging.

**Comment by DreamChaser-luzeyu** [comment]
Here is what I assigned and what I got:

![Screenshot_20240901_161112](https://github.com/user-attachments/assets/2c5ee972-8369-45ff-866a-c44c821fc578)

```
5: ztwrjywna7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc fq state UNKNOWN group default qlen 1000
    link/ether 7a:0d:b5:7f:10:3a brd ff:ff:ff:ff:ff:ff
    inet 10.0.222.133/16 brd 10.0.255.255 scope global ztwrjywna7
       valid_lft forever preferred_lft forever
    inet6 fdfe:520::1/32 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::780d:b5ff:fe7f:103a/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by kmahyyg** [comment]
Unfortunately, we aren't able to provide you with the help of zerotier usage.

Also: https://github.com/zerotier/ZeroTierOne/blob/f176e2539e10e8c0f61eb1d2e1f0e690a267a646/node/InetAddress.cpp#L29

Please try to enable this option:

![20240901-162345-Moonlight-009090@2x](https://github.com/user-attachments/assets/243047d0-e204-421c-908e-0f5b36abd6f2)

If you still be in such kind of trouble, I strongly recommend you to read their official document again.

**Comment by DreamChaser-luzeyu** [comment]
> Unfortunately, we aren't able to provide you with the help of zerotier usage.
> 
> Also: https://github.com/zerotier/ZeroTierOne/blob/f176e2539e10e8c0f61eb1d2e1f0e690a267a646/node/InetAddress.cpp#L29
> 
> Please try to enable this option:
> 
> ![20240901-162345-Moonlight-009090@2x](https://private-user-images.githubusercontent.com/16604643/363475939-243047d0-e204-421c-908e-0f5b36abd6f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxODExNzAsIm5iZiI6MTcyNTE4MDg3MCwicGF0aCI6Ii8xNjYwNDY0My8zNjM0NzU5MzktMjQzMDQ3ZDAtZTIwNC00MjFjLTkwOGUtMGY1YjM2YWJkNmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA4NTQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYTNmNzJmYWFjNDdjODJhZDYxZjE1NGJmMGIxNWI4ODA0MWJlNmI3MWM2YmUzMDk3ZDY2YWVhMjRmMTk2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wZ_soDGfpJ-U6ppekOaUc5adPK5lU1Ka4GyT61-Q7WQ)
> 
> If you still be in such kind of trouble, I strongly recommend you to read their official document again.

Thanks for your instruction. I did not notice it because I'm using ubuntu.
I've workaround it using radvd.

**Comment by kmahyyg** [comment]
RTFM: https://docs.zerotier.com/config/#network-idlocalconf-text-file-with-the-networks-settings
