### ISSUE TITLE
[BUG?]controller join the network

### ISSUE THREAD

**Issue by Mobiusa** [kmahyyg/ztncui-aio#37]
1. I've noticed that every time I specify a member's IPv4 in the console, the modified member device loses connection. It only regains connectivity after restarting ZeroTier on that device to obtain a new IP. This doesn't happen with the ztncui image. Of course, your project can automatically generate planets, which is more powerful and convenient.

2. I tried to make the main controller join the network by entering the container and using the command zerotier-cli join xxxx. It did join and was assigned an IP in the console. I then restarted ZeroTier inside the container, but no new network interface appeared in the container, and it didn't obtain an IP. However, listpeers can show the online information of other nodes.
![1](https://github.com/user-attachments/assets/57b80550-0ff6-44aa-ac10-96634e0bc064)
![2](https://github.com/user-attachments/assets/1699647f-6504-4c4c-8746-f10202aa2b95)

**Comment by kmahyyg** [comment]
Invalid issue. Not following template and search google before you ask.
