### ISSUE TITLE
A separate utility for generating a planet.custom file

### ISSUE THREAD

**Issue by X3il** [kmahyyg/ztncui-aio#38]
Hi, it would be really cool if you could make a utility that would allow generating a planet.custom file without running a container. This utility would help a very large number of zerotier users to untie their networks from public roots, because the zerotier product itself is interesting, but the lack of a simple way to generate roots is very depressing and reduces the speed of the network (for example, in my city the fastest root has a ping of about 80-90, although I have the opportunity to install my roots, I cannot do this without specialized knowledge in the field of programming)
Specifically, I tested your ztncui-aio in conditions of no direct accessibility of nodes to each other and the root server perfectly transmits traffic through itself, everything works fine
The point is that I already have a filled ztncui from the original key-networks repository and transferring it to docker and adding roots there is too labor-intensive, without the existence of a separate utility for creating roots)
If it were, I would simply use it to generate my planet.custom file and throw it on the controller, and then distribute it to the nodes

**Comment by kmahyyg** [comment]
Actually, it is already there.

Just clone the whole repo and run this script, this is what you want:
https://github.com/kmahyyg/ztncui-aio/blob/68c1821f4c29c7e5c111cea1d8aea20f00792a89/build-gobinaries.sh#L23

Require golang compiler.

**Comment by X3il** [comment]
Thank you very much, now I'll figure out mkworld.config.json a little and try to generate the file
Compile worked)

**Comment by kmahyyg** [comment]
> Thank you very much, now I'll figure out mkworld.config.json a little and try to generate the file Compile worked)

 Just a short reminder, unfortunately, golang builtin JSON parse does NOT support JSON5 (here, JSON with comments), please remove all comments if you tried to copy the sample from the README of this repo.

I'll close the issue for now, feel free to reopen it if you encounter any other problems.
